# Site settings
title: JayDBee
email: your-email@example.com
description: >-
  Welcome to my personal website featuring catalogs and lessons.
baseurl: "JayDBee.github.io"
url: ""

# Build settings
theme: minima
plugins:
  - jekyll-feed

# Collections
collections:
  interpretations:
    output: true
    #permalink: /interpretations/:name/

# Exclude from processing
exclude:
  - .sass-cache/
  - .jekyll-cache/
  - gemfiles/
  - Gemfile
  - Gemfile.lock
  - vendor/
#   - node_modules/
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
